{
 "title": "COVID-19 Global Dashboard",
 "tags": [
  "covid19",
  "global"
 ],
 "time": { "from": "2020-01-22T00:00:00.000Z", "to": "2022-05-14T00:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "DS_POSTGRES", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  {
   "title": "Total des Cas Confirmés",
   "type": "stat",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(total_confirmed) AS total_cases\nFROM (\n    SELECT DISTINCT ON (country) country, total_confirmed\n    FROM covid19_data\n    WHERE date <= NOW()\n    ORDER BY country, date DESC\n) AS latest;\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    country AS location,\n    MAX(total_confirmed) AS value\nFROM\n    covid19_data\nGROUP BY\n    country;\n"
    }
   ]
  },
  {
   "title": "Évolution des Cas et Décès dans le Temps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n    date::timestamp AS time,\n    SUM(daily_new_cases) AS new_cases,\n    SUM(daily_new_deaths) AS new_deaths\nFROM (\n    SELECT DISTINCT ON (country, date)\n        country,\n        date,\n        daily_new_cases,\n        daily_new_deaths\n    FROM covid19_data\n    ORDER BY country, date DESC\n) AS latest_data\nGROUP BY time\nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Répartition Mortalité et Récupération par Continent",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    continent,\n    AVG(latest_data.summary_mortality_rate) AS mortality,\n    AVG(latest_data.summary_recovery_rate) AS recovery\nFROM (\n    SELECT DISTINCT ON (country) \n        country, \n        continent, \n        summary_mortality_rate, \n        summary_recovery_rate, \n        date\n    FROM covid19_data\n    ORDER BY country, date DESC\n) AS latest_data\nGROUP BY continent;\n"
    }
   ]
  },
  {
   "title": "Top 10 Pays par Cas Confirmés",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \n    country, \n    MAX(total_confirmed) AS confirmed\nFROM \n    covid19_data\nGROUP BY \n    country\nORDER BY \n    confirmed DESC\nLIMIT 10;\n"
    }
   ]
  }
 ]
}