version: '3.9'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=msprdb
      - DB_USER=user
      - DB_PASSWORD=password
