@startuml

' Table WhoRegion
entity "WhoRegion" as wr {
  * short_code : VARCHAR(3)
  --
  name : TEXT
}

' Table Country
entity "Country" as c {
  * short_code : VARCHAR(3)
  --
  name : TEXT
  who_region_short_code : VARCHAR(3) [FK => WhoRegion.short_code]
}

' Table Disease
entity "Disease" as d {
  * id : INT
  --
  name : TEXT
}

' Table Vaccine
entity "Vaccine" as v {
  * id : INT
  --
  name : TEXT
  disease_id : INT [FK => Disease.id]
}

' Table WeeklyStatistics
entity "WeeklyStatistics" as ws {
  * id : INT
  --
  country_short_code : VARCHAR(3) [FK => Country.short_code]
  disease_id : INT [FK => Disease.id]
  date_of_report : DATE
  week_of_year : INT
  week_new_reported_cases : INT
  week_new_reported_deaths : INT
}

' Table DailyStatistics
entity "DailyStatistics" as ds {
  * id : INT
  --
  country_short_code : VARCHAR(3) [FK => Country.short_code]
  vaccine_id : INT [FK => Vaccine.id]
  date_of_report : DATE
  new_reported_doses : INT
}

' Définition des relations

' 1. Country est lié à WhoRegion (1-N)
wr ||--o{ c : "1 - N"

' 2. Country est lié à WeeklyStatistics (1-N)
c ||--o{ ws : "1 - N"

' 3. Country est lié à DailyStatistics (1-N)
c ||--o{ ds : "1 - N"

' 4. WeeklyStatistics est lié à Disease (N-1)
ws }o--|| d : "N - 1"

' 5. Vaccine est lié à Disease (N-1)
v }o--|| d : "N - 1"

' 6. DailyStatistics est lié à Vaccine (N-1)
ds }o--|| v : "N - 1"

@enduml
